  // src/ContaoManager/Plugin.php
    namespace Piethan\CloudFrontBundle\ContaoManager;
    
    use Contao\ManagerPlugin\Routing\RoutingPluginInterface;
    use Symfony\Component\Config\Loader\LoaderResolverInterface;
    use Symfony\Component\HttpKernel\KernelInterface;
    
    class Plugin implements RoutingPluginInterface
    {
      public function getRouteCollection(LoaderResolverInterface $resolver, KernelInterface $kernel)
      {
        $file = __DIR__.'/../Resources/config/routes.yaml';
        return $resolver->resolve($file)->load($file);
      }
    }
